# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 700)
        MainWindow.setStyleSheet("background-color: snow;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(30, 220, 720, 351))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setStyleSheet("background-color: white;")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 600, 220, 51))#zatrzymaj
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("background-color: white;")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 600, 170, 51))#wczytaj z urzadzenia
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet("background-color: white;")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 10, 371, 181))#dane
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.bytesize = QtWidgets.QComboBox(self.layoutWidget)
        self.bytesize.setObjectName("bytesize")
        self.gridLayout.addWidget(self.bytesize, 3, 1, 1, 1)
        self.bytesize.setStyleSheet("background-color: white;")
        self.baudrate = QtWidgets.QComboBox(self.layoutWidget)
        self.baudrate.setObjectName("baudrate")
        self.baudrate.setStyleSheet("background-color: white;")
        self.stopbits = QtWidgets.QComboBox(self.layoutWidget)
        self.stopbits.setObjectName("stopbits")
        self.stopbits.setStyleSheet("background-color: white;")
        self.gridLayout.addWidget(self.stopbits, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont("Times New Roman")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.parity = QtWidgets.QComboBox(self.layoutWidget)
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.parity.setObjectName("parity")
        self.gridLayout.addWidget(self.baudrate, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.parity, 0, 1, 1, 1)
        self.parity.setStyleSheet("background-color: white;")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 189, 100, 20)) #w przypadku
        font = QtGui.QFont("Times New Roman")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(550, 600, 150, 51))#zapiszjako
        self.save.setObjectName("save")
        self.save.setStyleSheet("background-color: white;")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(500, 40, 350, 101))#podpis
        font = QtGui.QFont("Times New Roman")
        font.setPointSize(13)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_6")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Etp- projekt 2"))
        self.pushButton.setText(_translate("MainWindow", "Zatrzymaj wczytywanie danych"))
        self.pushButton_2.setText(_translate("MainWindow", "Wczytaj z urządzenia"))
        self.label_4.setText(_translate("MainWindow", "Stopbits"))
        self.label_5.setText(_translate("MainWindow", "Rozmiar w bajtach"))
        self.label.setText(_translate("MainWindow", "Szybkość transmisji"))
        self.label_3.setText(_translate("MainWindow", "Parity"))
        self.label_6.setText(_translate("MainWindow", "Wyniki:"))
        self.save.setText(_translate("MainWindow", "Zapisz jako"))
        self.label_7.setText(_translate("MainWindow", "Wykonały:"+'\n'+ "Weronika Hebda"+'\n'+"Karolina Szostkiewicz"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
